# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Venues',
            new_name='Venue',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='comments',
            new_name='comment',
        ),
    ]
