# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_auto_20171106_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuetype',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
