# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_venuetype_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='total_vote_counts',
            new_name='total_vote_count',
        ),
    ]
