# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_auto_20171106_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='average_rating',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='total_vote_count',
        ),
        migrations.AddField(
            model_name='rating',
            name='total_vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
