# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0007_auto_20171108_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='sum_of_votes',
            field=models.IntegerField(default=0),
        ),
    ]
