# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 14:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venues', '0012_auto_20171109_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='sum_of_votes',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='total_vote_count',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('rated_by', 'venue')]),
        ),
    ]
