# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0013_auto_20171109_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venuetype',
            old_name='approved',
            new_name='is_approved',
        ),
    ]
